name = "atelier"
main = "worker.py"
compatibility_date = "2024-09-23"
compatibility_flags = ["python_workers"]

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"
