name = "atelier"
account_id = "6419a5847a11f496b1ba4f08ce43323d"
main = "worker.py"
compatibility_date = "2024-09-23"
compatibility_flags = ["python_workers"]

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"
